# Generated by Django 3.2.19 on 2025-09-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('consultation_type', models.CharField(choices=[('type1', 'General Inquiry'), ('type2', 'Technical Support'), ('type3', 'Aviation Investment Advisory'), ('type4', 'Making business with us'), ('type5', 'conferences and events'), ('type6', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
