# Generated by Django 3.2.19 on 2025-09-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_type',
            field=models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Technical Support', 'Technical Support'), ('Aviation Investment Advisory', 'Aviation Investment Advisory'), ('Making business with us', 'Making business with us'), ('conferences and events', 'conferences and events'), ('Other', 'Other')], max_length=50),
        ),
    ]
